version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - ./mongodb/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - Bluff_Tactics

  nestjs:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nestjs
    depends_on:
      - mongodb
    restart: always
    environment:
      MONGO_DB: ${MONGO_DB}
    ports:
      - "${NESTJS_PORT}:${NESTJS_PORT}"
    volumes:
      - ./backend:/app
    networks:
      - Bluff_Tactics
    tty: true
    command: bash -c "npm install && npm run start:dev"

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react
    depends_on:
      - nestjs
    restart: always
    ports:
      - "${REACT_PORT}:${REACT_PORT}"
    volumes:
      - ./frontend:/app
    environment:
      REACT_APP_PORT: ${REACT_PORT}
    networks:
      - Bluff_Tactics
    tty: true
    command: bash -c "npm install && npm run dev"

networks:
  Bluff_Tactics:
    driver: bridge
